name: Build & Push WebUI

on:
  push:
    branches: [ stage3/webui ]
    paths:
      - "webui/**"
      - "docker-compose.yml"
      - ".github/workflows/webui.yml"

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - uses: actions/checkout@v4

      # 2. Включаем Buildx (нужен для build-push-action)
      - uses: docker/setup-buildx-action@v3

      # 3. Логинимся в Docker Hub
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 4. Собираем и пушим образ
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: webui/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.REGISTRY_USER }}/financial-backtester-webui:${{ github.sha }}
